version: '3.8'

services:
  # Api Gateway
  api-gateway:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - "${API_GATEWAY_PORT}:8080"
    environment:
      USER_SERVICE_URI: ${USER_SERVICE_URI}
      AUTH_SERVICE_URI: ${AUTH_SERVICE_URI}
      ORDER_SERVICE_URI: ${ORDER_SERVICE_URI}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    depends_on:
      user-service:
        condition: service_healthy
      auth-service:
        condition: service_healthy
    networks:
      - public
      - internal

  # Services
  user-service:
    image: user-service
    expose:
      - "${USER_SERVICE_PORT}"
    environment:
      DB_HOST: ${USER_SERVICE_DB_HOST}
      DB_PORT: ${USER_SERVICE_DB_PORT}
      DB_USERNAME: ${USER_SERVICE_DB_USERNAME}
      DB_PASSWORD: ${USER_SERVICE_DB_PASSWORD}
      DB_NAME: ${USER_SERVICE_DB_NAME}
      REDIS_HOST: ${USER_SERVICE_REDIS_HOST}
      REDIS_PORT: ${USER_SERVICE_REDIS_PORT}
    depends_on:
      user_db:
        condition: service_healthy
      user_cache:
        condition: service_healthy
    networks:
      - internal

  auth-service:
    image: auth-service
    expose:
      - "${AUTH_SERVICE_PORT}"
    environment:
      DB_HOST: ${AUTH_SERVICE_DB_HOST}
      DB_USERNAME: ${AUTH_SERVICE_DB_USERNAME}
      DB_PASSWORD: ${AUTH_SERVICE_DB_PASSWORD}
      DB_NAME: ${AUTH_SERVICE_DB_NAME}
      DB_PORT: ${AUTH_SERVICE_DB_PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ACCESS_TOKEN_EXPIRATION: ${JWT_ACCESS_TOKEN_EXPIRATION}
      JWT_REFRESH_TOKEN_EXPIRATION: ${JWT_REFRESH_TOKEN_EXPIRATION}
    depends_on:
      auth_db:
        condition: service_healthy
    networks:
      - internal

  # Databases
  user_db:
    image: postgres:17-alpine
    expose:
      - "${USER_SERVICE_DB_PORT}"
    environment:
      POSTGRES_USER: ${USER_SERVICE_DB_USERNAME}
      POSTGRES_PASSWORD: ${USER_SERVICE_DB_PASSWORD}
      POSTGRES_DB: ${USER_SERVICE_DB_NAME}
    volumes:
      - user_data:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${USER_SERVICE_DB_USERNAME} -d ${USER_SERVICE_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  auth_db:
    image: postgres:17-alpine
    expose:
      - "${AUTH_SERVICE_DB_PORT}"
    environment:
      POSTGRES_USER: ${AUTH_SERVICE_DB_USERNAME}
      POSTGRES_PASSWORD: ${AUTH_SERVICE_DB_PASSWORD}
      POSTGRES_DB: ${AUTH_SERVICE_DB_NAME}
    volumes:
      - auth_data:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${AUTH_SERVICE_DB_USERNAME} -d ${AUTH_SERVICE_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  user_cache:
    image: redis:7.0-alpine
    expose:
      - "${USER_SERVICE_REDIS_PORT}"
    volumes:
      - user_cache_data:/data
    networks:
      - internal
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

# Networks
networks:
  public:
    external: true
    name: inno-public-network
  internal:
    driver: bridge
    internal: true

volumes:
  user_data:
    name: ${USER_SERVICE_NAME}_db_data
  auth_data:
    name: ${AUTH_SERVICE_NAME}_db_data
  user_cache_data:
    name: ${REDIS_SERVICE_NAME}_db_data